// AUTO-GENERATED by tools/gen_profiles.py. DO NOT EDIT.
#pragma once
#include <stdint.h>

static const uint8_t GOLDEN_DS35Q1GA_BLOB[] = {68,83,51,53,81,49,71,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,8,0,0,64,0,0,0,64,0,0,0,0,4,0,0,19,11,15,31,192,176,4,4,3,0,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,1,2,176,1,0,228,12,0,2,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
static const unsigned GOLDEN_DS35Q1GA_LEN = sizeof(GOLDEN_DS35Q1GA_BLOB);
