"""Generate the resident active_profile_t array and the golden test blob."""
import os
import chipdb


def _c_initializer(flat):
    def arr(vals):
        return "{" + ",".join(str(v) for v in vals) + "}"
    return (
        '{ "%s", %d,%d,%d,%d, %d,%d,%d,%d,%d,%d, %d, %d,%d, %s, %d, %d,%d, %d,%d, %d, %d, '
        '%d,%d,%d, %d,%d, %s, %s }'
    ) % (
        flat["name"], flat["page_size"], flat["spare_size"], flat["pages_per_block"],
        flat["total_blocks"], flat["op_page_read"], flat["op_read_cache"], flat["op_get_feat"],
        flat["op_set_feat"], flat["op_status_addr"], flat["op_cfg_addr"], flat["ecc_en_bit"],
        flat["ecc_shift"], flat["ecc_mask"], arr(flat["ecc_map"]), flat["status2_reg"],
        flat["id_method"], flat["id_n_bytes"], flat["qe_addr"], flat["qe_bit"],
        flat["read_mode"], flat["vcc_mv"], flat["bbm_off"], flat["bbm_len"], flat["bbm_good"],
        flat["oob_free_n"], flat["oob_ecc_n"], arr(flat["oob_free"]), arr(flat["oob_ecc"]),
    )


def render_resident(db):
    prof_rows, id_rows = [], []
    for name, c in sorted(db.chips.items()):
        if c.get("resident"):
            chip = chipdb.get(db, name)
            prof_rows.append("  " + _c_initializer(chipdb.flatten(chip)))
            idd = chip["id"]
            id_rows.append("  { 0x%02X, 0x%02X, 0x%02X }"
                           % (idd["mfr"], idd["dev"], idd.get("dev2") or 0))
    return (
        "// AUTO-GENERATED by tools/gen_profiles.py. DO NOT EDIT.\n"
        "#pragma once\n#include \"nand_profile.h\"\n\n"
        "static const active_profile_t PROFILES[] = {\n" + ",\n".join(prof_rows) + "\n};\n"
        "static const struct { uint8_t mfr, dev, dev2; } PROFILE_IDS[] = {\n"
        + ",\n".join(id_rows) + "\n};\n"
        "static const unsigned PROFILES_COUNT = sizeof(PROFILES)/sizeof(PROFILES[0]);\n"
    )


def render_golden(db, chip_name):
    blob = chipdb.pack(chipdb.flatten(chipdb.get(db, chip_name)))
    sym = "GOLDEN_" + chip_name.upper()
    body = ",".join(str(b) for b in blob)
    return (
        "// AUTO-GENERATED by tools/gen_profiles.py. DO NOT EDIT.\n"
        "#pragma once\n#include <stdint.h>\n\n"
        f"static const uint8_t {sym}_BLOB[] = {{{body}}};\n"
        f"static const unsigned {sym}_LEN = sizeof({sym}_BLOB);\n"
    )


def generate():
    db = chipdb.load()
    resident_out = "src/nand_profiles_generated.h"
    golden_out = "test/test_profile/golden_ds35.h"
    os.makedirs(os.path.dirname(golden_out), exist_ok=True)
    with open(resident_out, "w") as f:
        f.write(render_resident(db))
    with open(golden_out, "w") as f:
        f.write(render_golden(db, "DS35Q1GA"))
    print(f"[gen_profiles] wrote {resident_out} and {golden_out}")


try:
    Import("env")  # type: ignore  # noqa: F821 — injected by PlatformIO/SCons
    try:
        import yaml  # noqa: F401
    except ImportError:
        env.Execute("$PYTHONEXE -m pip install pyyaml")  # type: ignore  # noqa: F821
    generate()
except NameError:
    pass

if __name__ == "__main__":
    generate()
