"""Generate src/nand_profiles_generated.h from the chip database (db/).

Emits every `resident: true` chip as a pre-flattened `active_profile_t`
initializer. Flattening and the tier-2/3 checks come from tools/chipdb.py, so a
resident chip and a pushed chip are byte-identical, and a bad profile fails the
build here rather than on the device (design § 4.3).

Runs standalone (`python tools/gen_profiles.py [out.h]`) and as a PlatformIO
pre: hook (extra_scripts).
"""
import os
import sys

try:
    _HERE = os.path.dirname(os.path.abspath(__file__))
except NameError:   # PlatformIO/SCons runs extra_scripts without __file__
    _HERE = os.path.join(os.getcwd(), "tools")
sys.path.insert(0, _HERE)
import chipdb  # noqa: E402

DEFAULT_OUT = os.path.join(chipdb.REPO, "src", "nand_profiles_generated.h")
GOLDEN_OUT = os.path.join(chipdb.REPO, "test", "test_profile", "golden_blobs.h")
# Two NAND chips, a 3-byte and a 4-byte (native opcode) SPI NOR chip, an I2C
# EEPROM with address bits in the device address and a SPI EEPROM with A8 in
# the opcode.
GOLDEN_CHIPS = ("DS35Q1GA", "MT29F2G01ABAGD", "W25Q128.V", "MX25L25635F", "24CM02",
                "25xx040")


def _hex(v):
    return "0x%02X" % v


def _row(f):
    ecc_map = ", ".join(str(s) for s in f["ecc_map"])
    free = ", ".join(str(v) for v in f["oob_free"])
    ecc = ", ".join(str(v) for v in f["oob_ecc"])
    if f["family"] in chipdb.EEPROM_FAMILIES:
        what = "%s, %d B, %d-byte address" % (
            f["family"], f["size_bytes"], f["addr_bytes"])
        if f["dev_addr_bits"]:
            what += " + %d bit(s) at %d" % (f["dev_addr_bits"], f["dev_addr_shift"])
    elif f["family"] == "spi-nor":
        what = "%s profile, %d KiB, %d-byte address" % (
            f["profile"], f["size_bytes"] >> 10, f["addr_bytes"])
    else:
        what = "%s profile, %s ECC" % (f["profile"], f["ecc_scheme"])
    return (
        "  { // %s: %s\n"
        '    "%s", %s, %s, %s, %s,\n'
        "    %d, %d, %d, %d,\n"
        "    %s, %s, %s, %s, %s, %s, %s,\n"
        "    %d, %d, %s, { %s },\n"
        "    %s, %d, %d, %s, %s, %d, %d, %d,\n"
        "    %d,\n"
        "    %d, %d, %s, %d, %d, %s,\n"
        "    { %s },\n"
        "    { %s },\n"
        "    %d, %d, %d, %d, %d, %d, %d, { 0 } }"
        % (f["name"], what,
           f["name"], _hex(f["id_mfr"]), _hex(f["id_dev"]), _hex(f["id_dev2"]),
           _hex(f["id_flags"]),
           f["page_size"], f["spare_size"], f["pages_per_block"], f["total_blocks"],
           _hex(f["op_page_read"]), _hex(f["op_read_cache"]), _hex(f["op_read_cache_x4"]),
           _hex(f["op_get_feat"]), _hex(f["op_set_feat"]), _hex(f["op_status_addr"]),
           _hex(f["op_cfg_addr"]),
           f["ecc_en_bit"], f["ecc_shift"], _hex(f["ecc_mask"]), ecc_map,
           _hex(f["status2_reg"]), f["id_method"], f["id_n_bytes"], _hex(f["qe_addr"]),
           _hex(f["qe_bit"]), f["read_mode"], f["planes"], f["family_code"],
           f["vcc_mv"],
           f["bbm_off"], f["bbm_len"], _hex(f["bbm_good"]), f["oob_free_n"], f["oob_ecc_n"],
           _hex(f["bbm_pages"]), free, ecc,
           f["addr_bytes"], f["addr4_mode"], f["dummy_x1"], f["dummy_x4"], f["qer"],
           f["dev_addr_bits"], f["dev_addr_shift"]))


def render_header(db):
    flats, _ = chipdb.validate_db(db)          # raises ChipDBError on a bad chip
    resident = [f for f in flats.values() if f["resident"]]
    if not resident:
        raise chipdb.ChipDBError("no resident chips: tag at least one `resident: true`")
    rows = ",\n".join(_row(f) for f in resident)
    return (
        "// AUTO-GENERATED from db/ by tools/gen_profiles.py. DO NOT EDIT.\n"
        "// Field order: active_profile_t in src/nand_profile.h (schema v%d).\n"
        "#pragma once\n"
        '#include "nand_profile.h"\n\n'
        "static const active_profile_t NAND_RESIDENT[] = {\n%s\n};\n"
        "static const unsigned NAND_RESIDENT_COUNT =\n"
        "    sizeof(NAND_RESIDENT) / sizeof(NAND_RESIDENT[0]);\n"
        % (chipdb.SCHEMA_VER, rows))


def golden_ident(name):
    """C identifier suffix for a chip name (W25Q128.V -> W25Q128_V)."""
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def render_golden(db):
    """PRF push blobs packed by chipdb.py, for the native golden-blob test."""
    out = ["// AUTO-GENERATED by tools/gen_profiles.py --golden. DO NOT EDIT.",
           "// PRF blobs packed by tools/chipdb.py; test_profile unpacks them in C.",
           "#pragma once", "#include <stdint.h>", ""]
    for name in GOLDEN_CHIPS:
        blob = chipdb.pack_blob(chipdb.flatten(db, name))
        rows = ["  " + ", ".join("0x%02X" % b for b in blob[i:i + 12]) + ","
                for i in range(0, len(blob), 12)]
        out += ["static const uint8_t GOLDEN_%s[%d] = {" % (golden_ident(name), len(blob))]
        out += rows + ["};", ""]
    return "\n".join(out)


def generate(out_path=DEFAULT_OUT, db_root=chipdb.DB_DIR):
    header = render_header(chipdb.load_db(db_root))
    with open(out_path, "w") as f:
        f.write(header)
    print(f"[gen_profiles] wrote {out_path} ({header.count('  { //')} resident chips)")


# PlatformIO pre: hook entry point
try:
    Import("env")  # type: ignore  # noqa: F821 — injected by PlatformIO/SCons
    try:
        import yaml  # noqa: F401
    except ImportError:
        env.Execute("$PYTHONEXE -m pip install pyyaml")  # type: ignore # noqa: F821
    try:
        generate()
    except chipdb.ChipDBError as e:
        sys.stderr.write(f"[gen_profiles] chip database error: {e}\n")
        env.Exit(1)  # type: ignore # noqa: F821
except NameError:
    pass

if __name__ == "__main__":
    if sys.argv[1:2] == ["--golden"]:
        with open(GOLDEN_OUT, "w") as fh:
            fh.write(render_golden(chipdb.load_db()))
        print(f"[gen_profiles] wrote {GOLDEN_OUT}")
    else:
        generate(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT)
