// AUTO-GENERATED by tools/gen_profiles.py. DO NOT EDIT.
#pragma once
#include "nand_profile.h"

static const active_profile_t PROFILES[] = {
  { "DS35Q1GA", 2112,64,64,1024, 19,11,15,31,192,176, 4, 4,3, {0,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3}, 0, 1,2, 176,1, 0, 3300, 0,2,255, 0,0, {0,0,0,0,0,0,0,0}, {0,0,0,0,0,0,0,0} },
  { "MT29F2G01ABAGD", 2176,128,64,2048, 19,11,15,31,192,176, 4, 4,7, {0,1,3,2,3,2,3,3,3,3,3,3,3,3,3,3}, 0, 1,2, 0,0, 0, 3300, 0,1,255, 0,0, {0,0,0,0,0,0,0,0}, {0,0,0,0,0,0,0,0} }
};
static const unsigned PROFILES_COUNT = sizeof(PROFILES)/sizeof(PROFILES[0]);
